// src/modules/riskAssesment/constants.js

export const CONTROL_MAPPING = {
  // --- SECTION 5 CONTROLS (already shared earlier) ---
  "5.1": "Policies for information security :\n Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel and relevant interested parties, and reviewed at planned intervals and if significant changes occur.",
  "5.2": "Information security roles and responsibilities :\n Information security roles and responsibilities shall be defined and allocated according to the organization needs.",
  "5.3": "Segregation of duties :\n Conflicting duties and conflicting areas of responsibility shall be segregated.",
  "5.4": "Management responsibilities :\n Management shall require all personnel to apply information security in accordance with the established information security policy, topic-specific policies and procedures of the organization.",
  "5.5": "Contact with authorities :\n The organization shall establish and maintain contact with relevant authorities.",
  "5.6": "Contact with special interest groups :\n The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.",
  "5.7": "Threat intelligence :\n Information relating to information security threats shall be collected and analysed to produce threat intelligence.",
  "5.8": "Information security in project management :\n Information security shall be integrated into project management.",
  "5.9": "Inventory of information and other associated assets :\n An inventory of information and other associated assets, including owners, shall be developed and maintained.",
  "5.10": "Acceptable use of information and other associated assets :\n Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.",
  "5.11": "Return of assets :\n Personnel and other interested parties as appropriate shall return all the organization’s assets in their possession upon change or termination of their employment, contract or agreement.",
  "5.12": "Classification of information :\n Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.",
  "5.13": "Labelling of information :\n An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.",
  "5.14": "Information transfer :\n Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.",
  "5.15": "Access control :\n Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.",
  "5.16": "Identity management :\n The full life cycle of identities shall be managed.",
  "5.17": "Authentication information :\n Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.",
  "5.18": "Access rights :\n Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control.",
  "5.19": "Information security in supplier relationships :\n Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier’s products or services.",
  "5.20": "Addressing information security within supplier agreements :\n Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.",
  "5.21": "Managing information security in the ICT supply chain :\n Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.",
  "5.22": "Monitoring, review and change management of supplier services :\n The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.",
  "5.23": "Information security for use of cloud services :\n Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization’s information security requirements.",
  "5.24": "Information security incident management planning and preparation :\n The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.",
  "5.25": "Assessment and decision on information security events :\n The organization shall assess information security events and decide if they are to be categorized as information security incidents.",
  "5.26": "Response to information security incidents :\n Information security incidents shall be responded to in accordance with the documented procedures.",
  "5.27": "Learning from information security incidents :\n Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.",
  "5.28": "Collection of evidence :\n The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.",
  "5.29": "Information security during disruption :\n The organization shall plan how to maintain information security at an appropriate level during disruption.",
  "5.30": "ICT readiness for business continuity :\n ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.",
  "5.31": "Legal, statutory, regulatory and contractual requirements :\n Legal, statutory, regulatory and contractual requirements relevant to information security and the organization’s approach to meet these requirements shall be identified, documented and kept up to date.",
  "5.32": "Intellectual property rights :\n The organization shall implement appropriate procedures to protect intellectual property rights.",
  "5.33": "Protection of records :\n Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.",
  "5.34": "Privacy and protection of personal identifiable information (PII) :\n The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations and contractual requirements.",
  "5.35": "Independent review of information security :\n The organization’s approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.",
  "5.36": "Compliance with policies, rules and standards for information security :\n Compliance with the organization’s information security policy, topic-specific policies, rules and standards shall be regularly reviewed.",
  "5.37": "Documented operating procedures :\n Operating procedures for information processing facilities shall be documented and made available to personnel who need them.",

  // --- SECTION 6 CONTROLS (People Controls) ---
  "6.1": "Screening :\n Background verification checks on all candidates for employment shall be carried out in accordance with relevant laws, regulations and ethics and shall be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.",
  "6.2": "Terms and conditions of employment :\n The contractual agreements with employees and contractors shall state their and the organization’s responsibilities for information security.",
  "6.3": "Information security awareness, education and training :\n Personnel shall receive appropriate information security awareness, education and training and regular updates of the organization’s information security policy, topic-specific policies and procedures, as relevant for their job function.",
  "6.4": "Disciplinary process :\n A disciplinary process shall be formalized and communicated to take actions against personnel who have committed an information security breach.",
  "6.5": "Responsibilities after termination or change of employment :\n Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, communicated to the employee or contractor, and enforced.",
  "6.6": "Confidentiality or non-disclosure agreements :\n Confidentiality or non-disclosure agreements reflecting the organization’s needs for the protection of information shall be identified, regularly reviewed and documented.",
  "6.7": "Remote working :\n Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization’s premises.",
  "6.8": "Information security event reporting :\n Personnel shall be required to report observed or suspected information security events or weaknesses through appropriate channels in a timely manner.",

  // --- SECTION 7 CONTROLS ---
  "7.1": "Physical security perimeter :\n Security perimeters shall be defined and used to protect areas that contain either sensitive or critical information and information processing facilities.",
  "7.2": "Physical entry controls :\n Secure areas shall be protected by appropriate entry controls to ensure that only authorized personnel are allowed access.",
  "7.3": "Securing offices, rooms and facilities :\n Physical security for offices, rooms and facilities shall be designed and applied.",
  "7.4": "Physical security monitoring :\n Premises shall be continuously monitored for unauthorized physical access.",
  "7.5": "Protecting against physical and environmental threats :\n Protection shall be designed and implemented against physical and environmental threats.",
  "7.6": "Working in secure areas :\n Procedures for working in secure areas shall be designed and implemented.",
  "7.7": "Clear desk and clear screen :\n Clear desk and clear screen rules shall be defined and enforced.",
  "7.8": "Equipment siting and protection :\n Equipment shall be sited and protected to reduce the risks from environmental threats and hazards, and opportunities for unauthorized access.",
  "7.9": "Security of assets off-premises :\n Security shall be applied to assets off the organization’s premises.",
  "7.10": "Storage media :\n Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal.",
  "7.11": "Supporting utilities :\n Utility services shall be adequately protected.",
  "7.12": "Cabling security :\n Power and telecommunications cabling carrying data or supporting information services shall be protected against interception, interference or damage.",
  "7.13": "Equipment maintenance :\n Equipment shall be correctly maintained to ensure continued availability and integrity.",
  "7.14": "Secure disposal or re-use of equipment :\n Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.",
  "7.15": "Unattended user equipment :\n Unattended user equipment shall be protected.",
  "7.16": "Use of physical identifiers :\n The use of physical identifiers shall be managed.",
  "7.17": "Working remotely :\n Security measures shall be implemented when personnel are working remotely.",
  "7.18": "Mobile device management :\n Security measures shall be implemented to manage mobile devices.",

  // --- SECTION 8 CONTROLS ---
  "8.1": "User endpoint devices :\n Security measures shall be implemented on user endpoint devices.",
  "8.2": "Privileged access rights :\n The allocation and use of privileged access rights shall be restricted and managed.",
  "8.3": "Information access restriction :\n Access to information and other associated assets shall be restricted in accordance with the established topic-specific access control policy and access control rules.",
  "8.4": "Access to source code :\n Read and write access to source code, development tools and software libraries shall be appropriately restricted.",
  "8.5": "Secure authentication :\n Secure authentication techniques shall be implemented.",
  "8.6": "Capacity management :\n The use of resources shall be monitored, tuned and projections made of future capacity requirements to ensure the required system performance.",
  "8.7": "Protection against malware :\n Protection against malware shall be implemented and supported by appropriate user awareness.",
  "8.8": "Management of technical vulnerabilities :\n Procedures shall be defined and implemented to manage technical vulnerabilities.",
  "8.9": "Configuration management :\n Configuration items shall be identified, documented and managed.",
  "8.10": "Information deletion :\n Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.",
  "8.11": "Data masking :\n Data masking shall be used in accordance with the organization’s topic-specific policy on access control.",
  "8.12": "Data leakage prevention :\n Data leakage prevention measures shall be applied to systems, networks and devices that process, store or transmit sensitive information.",
  "8.13": "Information backup :\n Backup copies of information, software and systems shall be maintained and regularly tested.",
  "8.14": "Redundancy of information processing facilities :\n The organization shall implement redundancy for information processing facilities to meet availability requirements.",
  "8.15": "Logging :\n Logging shall be implemented to enable recording and examination of activities that may affect information security.",
  "8.16": "Monitoring activities :\n Networks, systems and applications shall be monitored for anomalous behaviour.",
  "8.17": "Clock synchronization :\n The clocks of information processing systems shall be synchronized to approved time sources.",
  "8.18": "Use of privileged utility programs :\n The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.",
  "8.19": "Installation of software on operational systems :\n Procedures shall be implemented to control the installation of software on operational systems.",
  "8.20": "Networks security management :\n Networks shall be managed and controlled to protect information in systems and applications.",
  "8.21": "Security of network services :\n Security mechanisms, service levels and management requirements of network services shall be identified, implemented and monitored.",
  "8.22": "Segregation of networks :\n Groups of information services, users and systems shall be segregated in networks.",
  "8.23": "Web filtering :\n Access to external websites shall be managed.",
  "8.24": "Use of cryptography :\n Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.",
  "8.25": "Secure development life cycle :\n Secure development life cycle processes shall be established and applied.",
  "8.26": "Application security requirements :\n Security requirements shall be identified and agreed prior to development and/or implementation of applications.",
  "8.27": "Secure system architecture and engineering principles :\n Principles for engineering secure systems shall be established, documented, maintained and applied.",
  "8.28": "Secure coding :\n Secure coding principles shall be applied when developing software.",
  "8.29": "Security testing in development and acceptance : Security testing processes shall be defined and implemented in the development life cycle.",
  "8.30": "Outsourced development :\n The organization shall direct, monitor and review the activities related to outsourced system development.",
  "8.31": "Separation of development, test and production environments :\n Development, testing and production environments shall be separated and secured.",
  "8.32": "Change management :\n Changes to information processing facilities and information systems shall be subject to change management procedures.",
  "8.33": "Test information :\n Test information shall be appropriately selected, protected and managed.",
  "8.34": "Protection of information systems during audit testing :\n Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management."
};
